// Placeholder data for scaffold pages.
export const placeholderStats = [
  { label: "Total Clients", value: "148", delta: "+12%", trend: "up" as const },
  { label: "Active Catalogs", value: "94", delta: "+4%", trend: "up" as const },
  { label: "Monthly Revenue", value: "$24,580", delta: "+8.2%", trend: "up" as const },
  { label: "Support Tickets", value: "12", delta: "-3%", trend: "down" as const },
];

export const placeholderBusinessStats = [
  { label: "Total Products", value: "312", delta: "+18", trend: "up" as const },
  { label: "Categories", value: "24", delta: "+2", trend: "up" as const },
  { label: "Subscribers", value: "1,842", delta: "+124", trend: "up" as const },
  { label: "Open Enquiries", value: "27", delta: "+5", trend: "up" as const },
];

export const placeholderClients = Array.from({ length: 8 }).map((_, i) => ({
  id: `c-${i + 1}`,
  name: [
    "Aurora Textiles",
    "Bloom & Co.",
    "Cedar Home",
    "Drift Coffee",
    "Ember Studio",
    "Fable Books",
    "Grove Ceramics",
    "Halo Beauty",
  ][i],
  email: `hello@company${i + 1}.com`,
  plan: ["Starter", "Growth", "Pro", "Enterprise"][i % 4],
  status: i % 3 === 0 ? "Trial" : "Active",
  createdAt: "Mar 12, 2025",
}));

export const placeholderBusinessSettings = {
  accountId: "ACC-8832",
  address: "123 Design Quarter, Ave 4",
  bannerUrl: "https://images.unsplash.com/photo-1441986300917-64674bd600d8",
  brandName: "Aurora Studio",
  city: "San Francisco",
  country: "USA",
  createdAt: "July 18, 2026 at 3:44:20 PM UTC+5:30",
  createdBy: "admin@aurora.com",
  emailAddress: "contact@aurorastudio.com",
  facebookLink: "https://facebook.com/aurorastudio",
  instagramLink: "https://instagram.com/aurorastudio",
  isEmailEnabled: true,
};

export const placeholderCategories = [
  {
    id: "cat-1",
    accountId: "ACC-8832",
    categoryName: "Apparel",
    description: "Thoughtfully tailored apparel and daily wardrobe essentials.",
    displayOrder: "1",
    imageUrl: "https://images.unsplash.com/photo-1489987707025-afc232f7ea0f",
    isActive: true,
    isDeleted: false,
    createdBy: "admin@aurora.com",
    createdAt: "July 18, 2026 at 3:48:08 PM UTC+5:30",
    updatedBy: "admin@aurora.com",
    updatedAt: "July 18, 2026 at 3:48:26 PM UTC+5:30",
  },
  {
    id: "cat-2",
    accountId: "ACC-8832",
    categoryName: "Accessories",
    description: "Handcrafted accessories to elevate your everyday outfit.",
    displayOrder: "2",
    imageUrl: "https://images.unsplash.com/photo-1523293182086-7651a899d37f",
    isActive: true,
    isDeleted: false,
    createdBy: "admin@aurora.com",
    createdAt: "July 18, 2026 at 3:48:08 PM UTC+5:30",
    updatedBy: "admin@aurora.com",
    updatedAt: "July 18, 2026 at 3:48:26 PM UTC+5:30",
  },
  {
    id: "cat-3",
    accountId: "ACC-8832",
    categoryName: "Home & Living",
    description: "Minimalist ceramic pieces and home decorations.",
    displayOrder: "3",
    imageUrl: "https://images.unsplash.com/photo-1513519245088-0e12902e5a38",
    isActive: true,
    isDeleted: false,
    createdBy: "admin@aurora.com",
    createdAt: "July 18, 2026 at 3:48:08 PM UTC+5:30",
    updatedBy: "admin@aurora.com",
    updatedAt: "July 18, 2026 at 3:48:26 PM UTC+5:30",
  },
  {
    id: "cat-4",
    accountId: "ACC-8832",
    categoryName: "Stationery",
    description: "Fine paper goods, linen notebooks and desk organization.",
    displayOrder: "4",
    imageUrl: "https://images.unsplash.com/photo-1544816155-12df9643f363",
    isActive: true,
    isDeleted: false,
    createdBy: "admin@aurora.com",
    createdAt: "July 18, 2026 at 3:48:08 PM UTC+5:30",
    updatedBy: "admin@aurora.com",
    updatedAt: "July 18, 2026 at 3:48:26 PM UTC+5:30",
  },
  {
    id: "cat-5",
    accountId: "ACC-8832",
    categoryName: "Beauty",
    description: "Organic self-care products and botanical fragrances.",
    displayOrder: "5",
    imageUrl: "https://images.unsplash.com/photo-1556228720-195a672e8a03",
    isActive: true,
    isDeleted: false,
    createdBy: "admin@aurora.com",
    createdAt: "July 18, 2026 at 3:48:08 PM UTC+5:30",
    updatedBy: "admin@aurora.com",
    updatedAt: "July 18, 2026 at 3:48:26 PM UTC+5:30",
  },
  {
    id: "cat-6",
    accountId: "ACC-8832",
    categoryName: "Gifts",
    description: "Curated gift sets for special occasions.",
    displayOrder: "6",
    imageUrl: "https://images.unsplash.com/photo-1549465220-1a8b9238cd48",
    isActive: false,
    isDeleted: false,
    createdBy: "admin@aurora.com",
    createdAt: "July 18, 2026 at 3:48:08 PM UTC+5:30",
    updatedBy: "admin@aurora.com",
    updatedAt: "July 18, 2026 at 3:48:26 PM UTC+5:30",
  },
];

export const placeholderProducts = Array.from({ length: 12 }).map((_, i) => ({
  id: `p-${i + 1}`,
  accountId: "ACC-8832",
  productName: [
    "Linen Everyday Shirt",
    "Ceramic Pour-Over",
    "Walnut Desk Tray",
    "Merino Wool Throw",
    "Brass Table Lamp",
    "Field Notebook",
    "Aromatic Candle",
    "Leather Cardholder",
    "Handwoven Basket",
    "Cotton Bath Towel",
    "Enamel Mug Set",
    "Silk Hair Scarf",
  ][i],
  categoryId: ["cat-1", "cat-2", "cat-3", "cat-4"][i % 4],
  description: "A beautifully crafted product from Aurora Studio.",
  imageUrls: ["https://images.unsplash.com/photo-1489987707025-afc232f7ea0f"],
  price: 24 + i * 7,
  sortOrder: i + 1,
  tagIds: ["t-1", "t-2"].slice(0, (i % 2) + 1),
  searchKeywords: ["aurora", "studio"],
  isActive: i % 5 !== 0,
  isDeleted: false,
  isStandalone: i % 4 === 0,
  createdBy: "admin@aurora.com",
  createdAt: "July 18, 2026 at 3:54:46 PM UTC+5:30",
  updatedBy: "admin@aurora.com",
  updatedAt: "July 18, 2026 at 3:55:10 PM UTC+5:30",
}));

export const placeholderTags = [
  {
    id: "t-1",
    accountId: "ACC-8832",
    tagName: "New",
    color: "#eab308",
    isDeleted: false,
    createdBy: "admin@aurora.com",
    createdAt: "July 18, 2026 at 3:50:26 PM UTC+5:30",
    updatedBy: "admin@aurora.com",
    updatedAt: "July 18, 2026 at 3:50:44 PM UTC+5:30",
  },
  {
    id: "t-2",
    accountId: "ACC-8832",
    tagName: "Bestseller",
    color: "#3b82f6",
    isDeleted: false,
    createdBy: "admin@aurora.com",
    createdAt: "July 18, 2026 at 3:50:26 PM UTC+5:30",
    updatedBy: "admin@aurora.com",
    updatedAt: "July 18, 2026 at 3:50:44 PM UTC+5:30",
  },
  {
    id: "t-3",
    accountId: "ACC-8832",
    tagName: "Limited",
    color: "#f97316",
    isDeleted: false,
    createdBy: "admin@aurora.com",
    createdAt: "July 18, 2026 at 3:50:26 PM UTC+5:30",
    updatedBy: "admin@aurora.com",
    updatedAt: "July 18, 2026 at 3:50:44 PM UTC+5:30",
  },
  {
    id: "t-4",
    accountId: "ACC-8832",
    tagName: "Sale",
    color: "#ef4444",
    isDeleted: false,
    createdBy: "admin@aurora.com",
    createdAt: "July 18, 2026 at 3:50:26 PM UTC+5:30",
    updatedBy: "admin@aurora.com",
    updatedAt: "July 18, 2026 at 3:50:44 PM UTC+5:30",
  },
];

export const placeholderSubscribers = Array.from({ length: 6 }).map((_, i) => ({
  id: `s-${i + 1}`,
  accountId: "ACC-8832",
  name: ["Anna Reyes", "Marcus Cole", "Priya Shah", "Leo Martins", "Sara Kim", "Jin Park"][i],
  email: `subscriber${i + 1}@mail.com`,
  phone: `+1 (555) 020-010${i}`,
  subscribedAt: "July 18, 2026 at 3:56:53 PM UTC+5:30",
  createdBy: "",
  createdAt: "July 18, 2026 at 3:57:11 PM UTC+5:30",
  updatedBy: "",
  updatedAt: "July 18, 2026 at 3:57:28 PM UTC+5:30",
}));

export const placeholderEnquiries = Array.from({ length: 5 }).map((_, i) => ({
  id: `e-${i + 1}`,
  accountId: "ACC-8832",
  customerName: ["Anna Reyes", "Marcus Cole", "Priya Shah", "Leo Martins", "Sara Kim"][i],
  email: `contact${i + 1}@mail.com`,
  phone: `+1 (555) 010-019${i}`,
  message: [
    "I would like to enquire about bulk ordering for the Linen Everyday Shirt.",
    "Do you offer international shipping to Canada?",
    "Can I customize the color scheme for a corporate gift order?",
    "Requesting product catalog sample pack and wholesale pricing details.",
    "Looking for store pickup options in San Francisco.",
  ][i],
  status: ["Pending", "In Progress", "Replied", "Closed", "Pending"][i],
  createdBy: "customer",
  createdAt: "July 18, 2026 at 4:00:58 PM UTC+5:30",
  updatedBy: "admin@aurora.com",
  updatedAt: "July 18, 2026 at 4:01:14 PM UTC+5:30",
}));

export const chartData = [
  { name: "Jan", value: 420 },
  { name: "Feb", value: 560 },
  { name: "Mar", value: 640 },
  { name: "Apr", value: 780 },
  { name: "May", value: 920 },
  { name: "Jun", value: 1050 },
  { name: "Jul", value: 1180 },
];
